//
// Created by Matthias Schicker (matthias@pocketsunited.com)
// on 6/14/13.
//


#import "FFGamesCore.h"
#import "FFGame.h"
#import "FFChallengeGenerator.h"
#import "FFPuzzleLoader.h"
#import "FFUtil.h"

@interface FFGamesCore ()
@property (strong, nonatomic) NSMutableDictionary *gamesById;
@property (strong, nonatomic) NSMutableDictionary *challengeByNumber;


@property (strong, nonatomic) FFPuzzleLoader *loader;
@property (strong, nonatomic) FFChallengeGenerator *generator;

@property (strong, nonatomic) NSMutableDictionary *challengeUnlockLevels;

@end

@implementation FFGamesCore {
}

// ////////////////////////////////////////////////////////////////////////
// StartUp

- (id)init {
    self = [super init];
    if (self) {
        self.gamesById = [[NSMutableDictionary alloc] initWithCapacity:10];
        self.challengeByNumber = [[NSMutableDictionary alloc] initWithCapacity:10];

        self.loader = [[FFPuzzleLoader alloc] init];
        self.generator = [[FFChallengeGenerator alloc] init];
    }
    return self;
}

- (FFGame *)autoGeneratedChallenge:(NSUInteger)level {
    FFGame* generated = [self.generator generateChallengeForLevel:level];
    [self registerGame:generated];

    return generated;
}

- (NSUInteger)unlockLevelForChallenge:(NSUInteger)challengeLevel {
    if (!self.challengeUnlockLevels){
        NSError * error;
        NSData *data = [NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"challenge_unlock_levels" ofType:@"txt"]];
        NSArray *unlockLevels = [NSJSONSerialization JSONObjectWithData:data options:kNilOptions error:&error];

        self.challengeUnlockLevels = [[NSMutableDictionary alloc] initWithCapacity:unlockLevels.count];
        int l = MAX(unlockLevels.count, [self autoGeneratedLevelCount]);
        for (int i = 0; i < l; i++){
            [self.challengeUnlockLevels
                    setObject:[unlockLevels objectAtIndex:(NSUInteger) MIN(i, unlockLevels.count - 1)]
                       forKey:@(i)];
        }
    }
    return [[self.challengeUnlockLevels objectForKey:@(challengeLevel)] unsignedIntegerValue];
}

- (NSInteger)indexForPuzzle:(FFGame *)game {
    for (int i = 0; i < [self puzzlesCount]; i++){
        FFGame *challenge = [self.challengeByNumber objectForKey:@(i)];
        if (challenge && [challenge.Id isEqualToString:game.Id]) return i;
    }
    return -1;
}

- (NSInteger)indexForChallenge:(FFGame *)game {
    if (!game.challengeIndex) return -1;
    return [game.challengeIndex intValue];
}

- (NSUInteger)puzzlesCount {
    return [self.loader numberOfChallenges];
}

- (NSUInteger)autoGeneratedLevelCount {
    return [self.generator levelCount];
}

- (FFGame *)puzzle:(NSUInteger)i {
    FFGame *challenge = [self.challengeByNumber objectForKey:[NSNumber numberWithUnsignedInteger:i]];
    if (!challenge){
        challenge = [self.loader loadLevel:i];
        [self.challengeByNumber setObject:challenge forKey:[NSNumber numberWithUnsignedInteger:i]];
        [self.gamesById setObject:challenge forKey:challenge.Id];
    }

    return challenge;
}

// StartUp
// ////////////////////////////////////////////////////////////////////////

- (void)registerGame:(FFGame *)game {
    [self.gamesById setObject:game forKey:game.Id];
}

- (FFGame *)generateNewHotSeatGame {
    FFGame *nuHotSeat = [[FFGame alloc] initHotSeat];
    [self registerGame:nuHotSeat];

    return nuHotSeat;
}

- (FFGame *)gameWithId:(NSString *)string {
    return [self.gamesById objectForKey:string];
}

// ////////////////////////////////////////////////////////////////////////
// Singleton

+ (FFGamesCore *)instance {
    static FFGamesCore *singleInstance;
    if (!singleInstance) {
        singleInstance = [[FFGamesCore alloc] init];
    }
    return singleInstance;
}

@end