//
// Created by Matthias Schicker (matthias@pocketsunited.com)
// on 10/9/13.
//


#import "FFStorageUtil.h"
#import "FFGamesCore.h"

#define FIRST_UNSOLVED_CHALLENGE_INDEX_KEY @"firstUnsolvedChallenge"
#define CHALLENGE_TIMES_PLAYED_KEY @"challengeTimesPlayed_%i"
#define CHALLENGE_TIMES_WON_KEY @"challengeTimesWon_%i"

@implementation FFStorageUtil {
}

static NSUInteger _firstUnsolvedChallengeIndex;
static NSMutableDictionary *_challengeTimesPlayed;
static NSMutableDictionary *_challengeTimesWon;


+ (NSUInteger)firstUnsolvedPuzzleIndex {
    if (_firstUnsolvedChallengeIndex < 1){
        _firstUnsolvedChallengeIndex = MAX(1,
            (NSUInteger) [[NSUserDefaults standardUserDefaults] integerForKey:FIRST_UNSOLVED_CHALLENGE_INDEX_KEY]);

        #ifdef DEBUG_ALL_ACCESS
        _firstUnsolvedChallengeIndex = 10;
        #endif
    }

    return _firstUnsolvedChallengeIndex;
}

+ (void)setFirstUnsolvedPuzzleIndex:(NSUInteger)nuIndex {
    if (nuIndex <= _firstUnsolvedChallengeIndex) return;    // can only be increased!

    _firstUnsolvedChallengeIndex = nuIndex;
    [[NSUserDefaults standardUserDefaults] setInteger:_firstUnsolvedChallengeIndex
                                               forKey:FIRST_UNSOLVED_CHALLENGE_INDEX_KEY];
    [[NSUserDefaults standardUserDefaults] synchronize];
}


//////////////////////////////////////////////////////////////////
// challenge times played.

+ (void)initTimesPlayedDictionary {
    _challengeTimesPlayed = [[NSMutableDictionary alloc] initWithCapacity:5];
    NSUInteger challengesCount =[[FFGamesCore instance] autoGeneratedLevelCount];
    for (NSUInteger i = 0; i < challengesCount; i++){
        NSString *key = [NSString stringWithFormat:CHALLENGE_TIMES_PLAYED_KEY, i];
        if (![[NSUserDefaults standardUserDefaults] objectForKey:key]) continue;

        NSInteger timesPlayed = [[NSUserDefaults standardUserDefaults] integerForKey:key];
        [_challengeTimesPlayed setObject:@(timesPlayed) forKey:@(i)];
    }
}

+ (NSUInteger)getTimesPlayedForChallengeLevel:(NSUInteger)level {
    if (!_challengeTimesPlayed) [FFStorageUtil initTimesPlayedDictionary];
    return [[_challengeTimesPlayed objectForKey:@(level)] unsignedIntegerValue];
}

+ (void)setTimesPlayed:(NSUInteger)timesPlayed forChallengeLevel:(NSUInteger)level {
    if (!_challengeTimesPlayed) [FFStorageUtil initTimesPlayedDictionary];
    [_challengeTimesPlayed setObject:@(timesPlayed) forKey:@(level)];

    // store it
    NSUInteger challengesCount =[[FFGamesCore instance] autoGeneratedLevelCount];
    for (NSUInteger i = 0; i < challengesCount; i++){
        [[NSUserDefaults standardUserDefaults]
                setInteger:[[_challengeTimesPlayed objectForKey:@(i)] integerValue]
                    forKey:[NSString stringWithFormat:CHALLENGE_TIMES_PLAYED_KEY, i]];
    }
}

//////////////////////////////////////////////////////////////////
// challenge levels won.

+ (void)initTimesWonDictionary {
    _challengeTimesWon = [[NSMutableDictionary alloc] initWithCapacity:5];
    NSUInteger challengesCount =[[FFGamesCore instance] autoGeneratedLevelCount];
    for (NSUInteger i = 0; i < challengesCount; i++){
        NSString *key = [NSString stringWithFormat:CHALLENGE_TIMES_WON_KEY, i];
        if (![[NSUserDefaults standardUserDefaults] objectForKey:key]) continue;

        NSInteger timesWon = [[NSUserDefaults standardUserDefaults] integerForKey:key];
        [_challengeTimesWon setObject:@(timesWon) forKey:@(i)];
    }
}

+ (NSUInteger)getTimesWonForChallengeLevel:(NSUInteger)level {
    if (!_challengeTimesWon) [FFStorageUtil initTimesWonDictionary];
    return [[_challengeTimesWon objectForKey:@(level)] unsignedIntegerValue];
}

+ (void)setTimesWon:(NSUInteger)timesWon forChallengeLevel:(NSUInteger)level {
    if (!_challengeTimesWon) [FFStorageUtil initTimesWonDictionary];
    [_challengeTimesWon setObject:@(timesWon) forKey:@(level)];

    // store it
    NSUInteger challengesCount =[[FFGamesCore instance] autoGeneratedLevelCount];
    for (NSUInteger i = 0; i < challengesCount; i++){
        [[NSUserDefaults standardUserDefaults]
                setInteger:[[_challengeTimesWon objectForKey:@(i)] integerValue]
                    forKey:[NSString stringWithFormat:CHALLENGE_TIMES_WON_KEY, i]];
    }
}

@end
